Milykh_Andrey_dz_2
shishkinav/2074_GB_Python_1- pull request #5
Opened 2022-01-24 10:50 UTC by amilykh

2022-01-24 11:08 UTC, amilykh commented
Добрый день, Анатолий!

Большое спасибо за занятия!  С вычислительной техникой работаю давно, 
но в  программировании делаю только первые шаги.  Вы это видите по
коду. Поэтому жду от Вас рекомендации по его улучшению!

2022-01-28 22:52 UTC, shishkinav requested changes

2022-01-28 22:52 UTC, shishkinav commented on Milykh_Andrey_dz_2/task_2_1.py
> +print(f'15 ** 2  = {15 ** 2}, тип результата выражения: {type(15 ** 2)}')
достаточно явно показали какие типы будут, спасибо ))

2022-01-28 22:52 UTC, shishkinav commented on Milykh_Andrey_dz_2/task_2_2.py
> +        if i_str.isnumeric():
знакомство с новыми методами строки - ОК

2022-01-28 22:52 UTC, shishkinav commented on Milykh_Andrey_dz_2/task_2_2.py
> +            list_out.append(list_in[i])
кода получилось очень много, посмотрите на разборе ДЗ на вебинаре, как можно по другому реализовать округление до двух знаков

2022-01-28 22:52 UTC, shishkinav commented on Milykh_Andrey_dz_2/task_2_3.py
> +            pass
если блока ветвления отвечающего за `False` нет, то его можно просто не писать, чтобы не ставить заглушку

2022-01-28 22:52 UTC, shishkinav commented on Milykh_Andrey_dz_2/task_2_4.py
> +
по заданию не требовалось работать со списком без изменения места хранения его в памяти, но спасибо, что предложили второй вариант

2022-01-28 22:52 UTC, shishkinav commented on Milykh_Andrey_dz_2/task_2_4.py
> +    return list_out  # Возвращается новый список
работает в соответствии с исходным заданием

2022-01-28 22:52 UTC, shishkinav commented on Milykh_Andrey_dz_2/task_2_5.py
> +    # print(f'list_out id: {id(list_out)}, list_in  = {list_out}')
можно было записать так `list_out = sorted(list_in, reverse=True)`

2022-01-28 22:52 UTC, shishkinav commented on Milykh_Andrey_dz_2/task_2_5.py
> +    return list_out  # list_out = ["список из пяти самых больших элементов"]
когда будем проходить вебинар по функциям, вернитесь и подумайте как можно было переиспользовать уже написанный код в других функциях здесь

2022-01-28 22:52 UTC, shishkinav approved these changes

2022-02-07 20:11 UTC, closed without merging